### ISSUE TITLE
How to consume accessus?

### ISSUE THREAD

**Issue by izzyreal** [hseeberger/accessus#13]
I can't figure out how to consume this library. I found out about it while watching https://www.youtube.com/watch?v=ryxrWVI3PMA

I tried to type along with all the code I saw, but I can't figure out how to make the `bindAndHandle` call work. I ended up copying your version of `Accessus.scala` into my project, but your `Demo` object is not available in your repository.

This is the error I'm getting:
![image](https://user-images.githubusercontent.com/3707432/65761387-fbb93c00-e11e-11e9-8e4d-0bdecd16923b.png)

It can't resolve symbol `->` and the squiggly line under `Any` is because:
![image](https://user-images.githubusercontent.com/3707432/65761486-27d4bd00-e11f-11e9-8fbe-a83c92566eb3.png)

Can you provide `Demo.scala` or include a line in your `README` that shows how to plug it in?

**Comment by hseeberger** [comment]
You are probably missing some implicit conversions. But anyway, this project is end of life – it has never been intended as production grade software and is no longer maintained.
